export const REVIEWS_LOAD_INITIATION = 'REVIEWS_LOAD_INITIATION';
export const REVIEWS_LOAD_SUCCESS = 'REVIEWS_LOAD_SUCCESS';
export const REVIEWS_LOAD_FAILURE = 'REVIEWS_LOAD_FAILURE';
export const ADD_REVIEW_INITIATION = 'ADD_REVIEW_INITIATION';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';
