export const RESTAURANTS_LOADING_INITIATION = 'RESTAURANTS_LOADING_INITIATION';
export const RESTAURANTS_LOADING_SUCCESS = 'RESTAURANTS_LOADING_SUCCESS';
export const RESTAURANTS_LOADING_FAILURE = 'RESTAURANTS_LOADING_FAILURE';
export const RESTAURANT_CATEGORIES = 'RESTAURANT_CATEGORIES';
export const CLEAR_RESTAURANT_ERRORS = 'CLEAR_RESTAURANT_ERRORS';
export const RESTAURANT_LOCATIONS = 'RESTAURANT_LOCATIONS';
